sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_admin:
    title:      "%site_name%"
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    dashboard:
        blocks:
            top:
                class: "col-xs-12"
                position: top
                type: sonata.block.service.text
                settings:
                    content: >
                        <div class='panel panel-default'>
                            <div class='panel-heading'>
                                <h3 class='panel-title'>Добро пожаловать!</h3>
                            </div>
                            <div class='panel-body'>
                                Вы вошли в панель управления сайтом <a href="%site_host%" target="_blank">&laquo;%site_name%&raquo;</a>.
                                Выберите материал для редактирования или создайте новый. Приятной работы!
                            </div>
                        </div>

            left:
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Order, Shop]

            right:
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Content, Config, sonata_user]

    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role

sonata_user:
    security_acl: false
    manager_type: orm
    admin:
        user:
            class:      Application\Sonata\UserBundle\Admin\UserAdmin

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

pix_sortable_behavior:
    db_driver: orm
    position_field:
        default: order