app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Liip imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# Sonata Configuration
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
