services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@service_container"

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ~
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    app.menu.catalog:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createCatalogMenu
        arguments: ~
        scope: request
        tags:
            - { name: knp_menu.menu, alias: catalog }

    app.menu.breadcrumbs:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createBreadcrumbsMenu
        arguments: ~
        scope: request
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }


    app.voter.request:
        class: AppBundle\Voter\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }

